// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: execution/v1/execution.proto

package execution

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum defining the current lifecycle state of an order.
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED      OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING          OrderStatus = 1
	OrderStatus_ORDER_STATUS_PARTIALLY_FILLED OrderStatus = 2
	OrderStatus_ORDER_STATUS_FILLED           OrderStatus = 3
	OrderStatus_ORDER_STATUS_CANCELED         OrderStatus = 4
	OrderStatus_ORDER_STATUS_REJECTED         OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_PARTIALLY_FILLED",
		3: "ORDER_STATUS_FILLED",
		4: "ORDER_STATUS_CANCELED",
		5: "ORDER_STATUS_REJECTED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":      0,
		"ORDER_STATUS_PENDING":          1,
		"ORDER_STATUS_PARTIALLY_FILLED": 2,
		"ORDER_STATUS_FILLED":           3,
		"ORDER_STATUS_CANCELED":         4,
		"ORDER_STATUS_REJECTED":         5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_v1_execution_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_execution_v1_execution_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{0}
}

// Enum defining the action type of the order request.
type OrderAction int32

const (
	OrderAction_ORDER_ACTION_UNSPECIFIED OrderAction = 0
	OrderAction_ORDER_ACTION_BUY         OrderAction = 1
	OrderAction_ORDER_ACTION_SELL        OrderAction = 2
)

// Enum value maps for OrderAction.
var (
	OrderAction_name = map[int32]string{
		0: "ORDER_ACTION_UNSPECIFIED",
		1: "ORDER_ACTION_BUY",
		2: "ORDER_ACTION_SELL",
	}
	OrderAction_value = map[string]int32{
		"ORDER_ACTION_UNSPECIFIED": 0,
		"ORDER_ACTION_BUY":         1,
		"ORDER_ACTION_SELL":        2,
	}
)

func (x OrderAction) Enum() *OrderAction {
	p := new(OrderAction)
	*p = x
	return p
}

func (x OrderAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderAction) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_v1_execution_proto_enumTypes[1].Descriptor()
}

func (OrderAction) Type() protoreflect.EnumType {
	return &file_execution_v1_execution_proto_enumTypes[1]
}

func (x OrderAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderAction.Descriptor instead.
func (OrderAction) EnumDescriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{1}
}

// Enum defining execution priority or rules.
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_MARKET      OrderType = 1 // Execute immediately at whatever price is available
	OrderType_ORDER_TYPE_LIMIT       OrderType = 2 // Execute only at the specified price or better
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_MARKET",
		2: "ORDER_TYPE_LIMIT",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_MARKET":      1,
		"ORDER_TYPE_LIMIT":       2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_v1_execution_proto_enumTypes[2].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_execution_v1_execution_proto_enumTypes[2]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{2}
}

// Individual order details streamed from the Strategy Agent.
type SubmitOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`             // Links the execution to a specific backtest run
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                   // Unique client-side generated UUID
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                                    // E.g., "ADANIPORTS", "ETERNAL"
	Action        OrderAction            `protobuf:"varint,4,opt,name=action,proto3,enum=api.execution.v1.OrderAction" json:"action,omitempty"` // BUY or SELL
	Type          OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=api.execution.v1.OrderType" json:"type,omitempty"`       // MARKET or LIMIT
	Quantity      float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`                              // Number of shares/tokens to trade
	LimitPrice    float64                `protobuf:"fixed64,7,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`        // Only evaluated if type = ORDER_TYPE_LIMIT
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderRequest) Reset() {
	*x = SubmitOrderRequest{}
	mi := &file_execution_v1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRequest) ProtoMessage() {}

func (x *SubmitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRequest.ProtoReflect.Descriptor instead.
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitOrderRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SubmitOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SubmitOrderRequest) GetAction() OrderAction {
	if x != nil {
		return x.Action
	}
	return OrderAction_ORDER_ACTION_UNSPECIFIED
}

func (x *SubmitOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *SubmitOrderRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SubmitOrderRequest) GetLimitPrice() float64 {
	if x != nil {
		return x.LimitPrice
	}
	return 0
}

func (x *SubmitOrderRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Summary of individual transactions executed inside the matching engine.
type OrderExecutionReceipt struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OrderId               string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol                string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Status                OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=api.execution.v1.OrderStatus" json:"status,omitempty"`
	RequestedQuantity     float64                `protobuf:"fixed64,4,opt,name=requested_quantity,json=requestedQuantity,proto3" json:"requested_quantity,omitempty"`
	FilledQuantity        float64                `protobuf:"fixed64,5,opt,name=filled_quantity,json=filledQuantity,proto3" json:"filled_quantity,omitempty"`
	AverageExecutionPrice float64                `protobuf:"fixed64,6,opt,name=average_execution_price,json=averageExecutionPrice,proto3" json:"average_execution_price,omitempty"` // Accounts for simulated slippage
	TransactionFees       float64                `protobuf:"fixed64,7,opt,name=transaction_fees,json=transactionFees,proto3" json:"transaction_fees,omitempty"`                     // Simulates exchange overhead costs
	RejectionReason       string                 `protobuf:"bytes,8,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`                       // Populated if status = ORDER_STATUS_REJECTED
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OrderExecutionReceipt) Reset() {
	*x = OrderExecutionReceipt{}
	mi := &file_execution_v1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderExecutionReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderExecutionReceipt) ProtoMessage() {}

func (x *OrderExecutionReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderExecutionReceipt.ProtoReflect.Descriptor instead.
func (*OrderExecutionReceipt) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *OrderExecutionReceipt) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderExecutionReceipt) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderExecutionReceipt) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderExecutionReceipt) GetRequestedQuantity() float64 {
	if x != nil {
		return x.RequestedQuantity
	}
	return 0
}

func (x *OrderExecutionReceipt) GetFilledQuantity() float64 {
	if x != nil {
		return x.FilledQuantity
	}
	return 0
}

func (x *OrderExecutionReceipt) GetAverageExecutionPrice() float64 {
	if x != nil {
		return x.AverageExecutionPrice
	}
	return 0
}

func (x *OrderExecutionReceipt) GetTransactionFees() float64 {
	if x != nil {
		return x.TransactionFees
	}
	return 0
}

func (x *OrderExecutionReceipt) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *OrderExecutionReceipt) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// The final server response returned once the client stream terminates.
type BatchExecutionReport struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TotalOrdersProcessed uint32                 `protobuf:"varint,2,opt,name=total_orders_processed,json=totalOrdersProcessed,proto3" json:"total_orders_processed,omitempty"`
	SuccessfulFills      uint32                 `protobuf:"varint,3,opt,name=successful_fills,json=successfulFills,proto3" json:"successful_fills,omitempty"`
	TotalVolumeExecuted  float64                `protobuf:"fixed64,4,opt,name=total_volume_executed,json=totalVolumeExecuted,proto3" json:"total_volume_executed,omitempty"`
	TotalFeesIncurred    float64                `protobuf:"fixed64,5,opt,name=total_fees_incurred,json=totalFeesIncurred,proto3" json:"total_fees_incurred,omitempty"`
	// A list of receipts containing details for every processed transaction in the batch
	Receipts      []*OrderExecutionReceipt `protobuf:"bytes,6,rep,name=receipts,proto3" json:"receipts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchExecutionReport) Reset() {
	*x = BatchExecutionReport{}
	mi := &file_execution_v1_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExecutionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExecutionReport) ProtoMessage() {}

func (x *BatchExecutionReport) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExecutionReport.ProtoReflect.Descriptor instead.
func (*BatchExecutionReport) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{2}
}

func (x *BatchExecutionReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BatchExecutionReport) GetTotalOrdersProcessed() uint32 {
	if x != nil {
		return x.TotalOrdersProcessed
	}
	return 0
}

func (x *BatchExecutionReport) GetSuccessfulFills() uint32 {
	if x != nil {
		return x.SuccessfulFills
	}
	return 0
}

func (x *BatchExecutionReport) GetTotalVolumeExecuted() float64 {
	if x != nil {
		return x.TotalVolumeExecuted
	}
	return 0
}

func (x *BatchExecutionReport) GetTotalFeesIncurred() float64 {
	if x != nil {
		return x.TotalFeesIncurred
	}
	return 0
}

func (x *BatchExecutionReport) GetReceipts() []*OrderExecutionReceipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

// Request payload to check account balances.
type AccountStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountStateRequest) Reset() {
	*x = AccountStateRequest{}
	mi := &file_execution_v1_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountStateRequest) ProtoMessage() {}

func (x *AccountStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountStateRequest.ProtoReflect.Descriptor instead.
func (*AccountStateRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{3}
}

func (x *AccountStateRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Response payload holding real-time balance metrics.
type AccountStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AvailableCash float64                `protobuf:"fixed64,2,opt,name=available_cash,json=availableCash,proto3" json:"available_cash,omitempty"` // Simulated fiat/base currency balance
	// Map tracking held assets -> quantity (e.g., {"ADANIPORTS": 150.0, "ETERNAL": 45.0})
	Positions     map[string]float64 `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountStateResponse) Reset() {
	*x = AccountStateResponse{}
	mi := &file_execution_v1_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountStateResponse) ProtoMessage() {}

func (x *AccountStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountStateResponse.ProtoReflect.Descriptor instead.
func (*AccountStateResponse) Descriptor() ([]byte, []int) {
	return file_execution_v1_execution_proto_rawDescGZIP(), []int{4}
}

func (x *AccountStateResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountStateResponse) GetAvailableCash() float64 {
	if x != nil {
		return x.AvailableCash
	}
	return 0
}

func (x *AccountStateResponse) GetPositions() map[string]float64 {
	if x != nil {
		return x.Positions
	}
	return nil
}

var File_execution_v1_execution_proto protoreflect.FileDescriptor

const file_execution_v1_execution_proto_rawDesc = "" +
	"\n" +
	"\x1cexecution/v1/execution.proto\x12\x10api.execution.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x02\n" +
	"\x12SubmitOrderRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x125\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1d.api.execution.v1.OrderActionR\x06action\x12/\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1b.api.execution.v1.OrderTypeR\x04type\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12\x1f\n" +
	"\vlimit_price\x18\a \x01(\x01R\n" +
	"limitPrice\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa2\x03\n" +
	"\x15OrderExecutionReceipt\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x125\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1d.api.execution.v1.OrderStatusR\x06status\x12-\n" +
	"\x12requested_quantity\x18\x04 \x01(\x01R\x11requestedQuantity\x12'\n" +
	"\x0ffilled_quantity\x18\x05 \x01(\x01R\x0efilledQuantity\x126\n" +
	"\x17average_execution_price\x18\x06 \x01(\x01R\x15averageExecutionPrice\x12)\n" +
	"\x10transaction_fees\x18\a \x01(\x01R\x0ftransactionFees\x12)\n" +
	"\x10rejection_reason\x18\b \x01(\tR\x0frejectionReason\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbf\x02\n" +
	"\x14BatchExecutionReport\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x124\n" +
	"\x16total_orders_processed\x18\x02 \x01(\rR\x14totalOrdersProcessed\x12)\n" +
	"\x10successful_fills\x18\x03 \x01(\rR\x0fsuccessfulFills\x122\n" +
	"\x15total_volume_executed\x18\x04 \x01(\x01R\x13totalVolumeExecuted\x12.\n" +
	"\x13total_fees_incurred\x18\x05 \x01(\x01R\x11totalFeesIncurred\x12C\n" +
	"\breceipts\x18\x06 \x03(\v2'.api.execution.v1.OrderExecutionReceiptR\breceipts\"S\n" +
	"\x13AccountStateRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xef\x01\n" +
	"\x14AccountStateResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12%\n" +
	"\x0eavailable_cash\x18\x02 \x01(\x01R\ravailableCash\x12S\n" +
	"\tpositions\x18\x03 \x03(\v25.api.execution.v1.AccountStateResponse.PositionsEntryR\tpositions\x1a<\n" +
	"\x0ePositionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01*\xb7\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12!\n" +
	"\x1dORDER_STATUS_PARTIALLY_FILLED\x10\x02\x12\x17\n" +
	"\x13ORDER_STATUS_FILLED\x10\x03\x12\x19\n" +
	"\x15ORDER_STATUS_CANCELED\x10\x04\x12\x19\n" +
	"\x15ORDER_STATUS_REJECTED\x10\x05*X\n" +
	"\vOrderAction\x12\x1c\n" +
	"\x18ORDER_ACTION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_ACTION_BUY\x10\x01\x12\x15\n" +
	"\x11ORDER_ACTION_SELL\x10\x02*T\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x01\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x022\xd8\x01\n" +
	"\x10ExecutionService\x12b\n" +
	"\x10SubmitOrderBatch\x12$.api.execution.v1.SubmitOrderRequest\x1a&.api.execution.v1.BatchExecutionReport(\x01\x12`\n" +
	"\x0fGetAccountState\x12%.api.execution.v1.AccountStateRequest\x1a&.api.execution.v1.AccountStateResponseB6Z4github.com/opticSquid/ticksim/execution/v1;executionb\x06proto3"

var (
	file_execution_v1_execution_proto_rawDescOnce sync.Once
	file_execution_v1_execution_proto_rawDescData []byte
)

func file_execution_v1_execution_proto_rawDescGZIP() []byte {
	file_execution_v1_execution_proto_rawDescOnce.Do(func() {
		file_execution_v1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_v1_execution_proto_rawDesc), len(file_execution_v1_execution_proto_rawDesc)))
	})
	return file_execution_v1_execution_proto_rawDescData
}

var file_execution_v1_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_execution_v1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_execution_v1_execution_proto_goTypes = []any{
	(OrderStatus)(0),              // 0: api.execution.v1.OrderStatus
	(OrderAction)(0),              // 1: api.execution.v1.OrderAction
	(OrderType)(0),                // 2: api.execution.v1.OrderType
	(*SubmitOrderRequest)(nil),    // 3: api.execution.v1.SubmitOrderRequest
	(*OrderExecutionReceipt)(nil), // 4: api.execution.v1.OrderExecutionReceipt
	(*BatchExecutionReport)(nil),  // 5: api.execution.v1.BatchExecutionReport
	(*AccountStateRequest)(nil),   // 6: api.execution.v1.AccountStateRequest
	(*AccountStateResponse)(nil),  // 7: api.execution.v1.AccountStateResponse
	nil,                           // 8: api.execution.v1.AccountStateResponse.PositionsEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_execution_v1_execution_proto_depIdxs = []int32{
	1, // 0: api.execution.v1.SubmitOrderRequest.action:type_name -> api.execution.v1.OrderAction
	2, // 1: api.execution.v1.SubmitOrderRequest.type:type_name -> api.execution.v1.OrderType
	9, // 2: api.execution.v1.SubmitOrderRequest.created_at:type_name -> google.protobuf.Timestamp
	0, // 3: api.execution.v1.OrderExecutionReceipt.status:type_name -> api.execution.v1.OrderStatus
	9, // 4: api.execution.v1.OrderExecutionReceipt.updated_at:type_name -> google.protobuf.Timestamp
	4, // 5: api.execution.v1.BatchExecutionReport.receipts:type_name -> api.execution.v1.OrderExecutionReceipt
	8, // 6: api.execution.v1.AccountStateResponse.positions:type_name -> api.execution.v1.AccountStateResponse.PositionsEntry
	3, // 7: api.execution.v1.ExecutionService.SubmitOrderBatch:input_type -> api.execution.v1.SubmitOrderRequest
	6, // 8: api.execution.v1.ExecutionService.GetAccountState:input_type -> api.execution.v1.AccountStateRequest
	5, // 9: api.execution.v1.ExecutionService.SubmitOrderBatch:output_type -> api.execution.v1.BatchExecutionReport
	7, // 10: api.execution.v1.ExecutionService.GetAccountState:output_type -> api.execution.v1.AccountStateResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_execution_v1_execution_proto_init() }
func file_execution_v1_execution_proto_init() {
	if File_execution_v1_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_v1_execution_proto_rawDesc), len(file_execution_v1_execution_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execution_v1_execution_proto_goTypes,
		DependencyIndexes: file_execution_v1_execution_proto_depIdxs,
		EnumInfos:         file_execution_v1_execution_proto_enumTypes,
		MessageInfos:      file_execution_v1_execution_proto_msgTypes,
	}.Build()
	File_execution_v1_execution_proto = out.File
	file_execution_v1_execution_proto_goTypes = nil
	file_execution_v1_execution_proto_depIdxs = nil
}
