// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: strategy/v1/strategy.proto

package strategy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Supported algorithmic types running inside the Go worker framework
type StrategyType int32

const (
	StrategyType_STRATEGY_TYPE_UNSPECIFIED              StrategyType = 0
	StrategyType_STRATEGY_TYPE_MOVING_AVERAGE_CROSSOVER StrategyType = 1
	StrategyType_STRATEGY_TYPE_MEAN_REVERSION           StrategyType = 2
	StrategyType_STRATEGY_TYPE_MOMENTUM                 StrategyType = 3
)

// Enum value maps for StrategyType.
var (
	StrategyType_name = map[int32]string{
		0: "STRATEGY_TYPE_UNSPECIFIED",
		1: "STRATEGY_TYPE_MOVING_AVERAGE_CROSSOVER",
		2: "STRATEGY_TYPE_MEAN_REVERSION",
		3: "STRATEGY_TYPE_MOMENTUM",
	}
	StrategyType_value = map[string]int32{
		"STRATEGY_TYPE_UNSPECIFIED":              0,
		"STRATEGY_TYPE_MOVING_AVERAGE_CROSSOVER": 1,
		"STRATEGY_TYPE_MEAN_REVERSION":           2,
		"STRATEGY_TYPE_MOMENTUM":                 3,
	}
)

func (x StrategyType) Enum() *StrategyType {
	p := new(StrategyType)
	*p = x
	return p
}

func (x StrategyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StrategyType) Descriptor() protoreflect.EnumDescriptor {
	return file_strategy_v1_strategy_proto_enumTypes[0].Descriptor()
}

func (StrategyType) Type() protoreflect.EnumType {
	return &file_strategy_v1_strategy_proto_enumTypes[0]
}

func (x StrategyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StrategyType.Descriptor instead.
func (StrategyType) EnumDescriptor() ([]byte, []int) {
	return file_strategy_v1_strategy_proto_rawDescGZIP(), []int{0}
}

// Current status of the agent's internal evaluation loop
type StrategyStatus int32

const (
	StrategyStatus_STRATEGY_STATUS_UNSPECIFIED StrategyStatus = 0
	StrategyStatus_STRATEGY_STATUS_IDLE        StrategyStatus = 1
	StrategyStatus_STRATEGY_STATUS_RUNNING     StrategyStatus = 2
	StrategyStatus_STRATEGY_STATUS_PAUSED      StrategyStatus = 3
	StrategyStatus_STRATEGY_STATUS_ERROR       StrategyStatus = 4
)

// Enum value maps for StrategyStatus.
var (
	StrategyStatus_name = map[int32]string{
		0: "STRATEGY_STATUS_UNSPECIFIED",
		1: "STRATEGY_STATUS_IDLE",
		2: "STRATEGY_STATUS_RUNNING",
		3: "STRATEGY_STATUS_PAUSED",
		4: "STRATEGY_STATUS_ERROR",
	}
	StrategyStatus_value = map[string]int32{
		"STRATEGY_STATUS_UNSPECIFIED": 0,
		"STRATEGY_STATUS_IDLE":        1,
		"STRATEGY_STATUS_RUNNING":     2,
		"STRATEGY_STATUS_PAUSED":      3,
		"STRATEGY_STATUS_ERROR":       4,
	}
)

func (x StrategyStatus) Enum() *StrategyStatus {
	p := new(StrategyStatus)
	*p = x
	return p
}

func (x StrategyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StrategyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_strategy_v1_strategy_proto_enumTypes[1].Descriptor()
}

func (StrategyStatus) Type() protoreflect.EnumType {
	return &file_strategy_v1_strategy_proto_enumTypes[1]
}

func (x StrategyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StrategyStatus.Descriptor instead.
func (StrategyStatus) EnumDescriptor() ([]byte, []int) {
	return file_strategy_v1_strategy_proto_rawDescGZIP(), []int{1}
}

type StrategyConfig struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StrategyId string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Type       StrategyType           `protobuf:"varint,2,opt,name=type,proto3,enum=api.strategy.v1.StrategyType" json:"type,omitempty"`
	// Risk control limits
	MaxPositionSize      float64 `protobuf:"fixed64,3,opt,name=max_position_size,json=maxPositionSize,proto3" json:"max_position_size,omitempty"`                // Maximum allowable quantity per symbol
	StopLossPercentage   float64 `protobuf:"fixed64,4,opt,name=stop_loss_percentage,json=stopLossPercentage,proto3" json:"stop_loss_percentage,omitempty"`       // Hard exit trigger limit (e.g., 0.02 for 2%)
	TakeProfitPercentage float64 `protobuf:"fixed64,5,opt,name=take_profit_percentage,json=takeProfitPercentage,proto3" json:"take_profit_percentage,omitempty"` // Target profit exit threshold
	// Flexible map for hyperparameters (e.g., short_window: "50", long_window: "200")
	Parameters    map[string]string `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyConfig) Reset() {
	*x = StrategyConfig{}
	mi := &file_strategy_v1_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyConfig) ProtoMessage() {}

func (x *StrategyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_v1_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyConfig.ProtoReflect.Descriptor instead.
func (*StrategyConfig) Descriptor() ([]byte, []int) {
	return file_strategy_v1_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *StrategyConfig) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *StrategyConfig) GetType() StrategyType {
	if x != nil {
		return x.Type
	}
	return StrategyType_STRATEGY_TYPE_UNSPECIFIED
}

func (x *StrategyConfig) GetMaxPositionSize() float64 {
	if x != nil {
		return x.MaxPositionSize
	}
	return 0
}

func (x *StrategyConfig) GetStopLossPercentage() float64 {
	if x != nil {
		return x.StopLossPercentage
	}
	return 0
}

func (x *StrategyConfig) GetTakeProfitPercentage() float64 {
	if x != nil {
		return x.TakeProfitPercentage
	}
	return 0
}

func (x *StrategyConfig) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type UpdateStrategyConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NewConfig     *StrategyConfig        `protobuf:"bytes,2,opt,name=new_config,json=newConfig,proto3" json:"new_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStrategyConfigRequest) Reset() {
	*x = UpdateStrategyConfigRequest{}
	mi := &file_strategy_v1_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStrategyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStrategyConfigRequest) ProtoMessage() {}

func (x *UpdateStrategyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_v1_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStrategyConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateStrategyConfigRequest) Descriptor() ([]byte, []int) {
	return file_strategy_v1_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStrategyConfigRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateStrategyConfigRequest) GetNewConfig() *StrategyConfig {
	if x != nil {
		return x.NewConfig
	}
	return nil
}

type UpdateStrategyConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStrategyConfigResponse) Reset() {
	*x = UpdateStrategyConfigResponse{}
	mi := &file_strategy_v1_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStrategyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStrategyConfigResponse) ProtoMessage() {}

func (x *UpdateStrategyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_v1_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStrategyConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateStrategyConfigResponse) Descriptor() ([]byte, []int) {
	return file_strategy_v1_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateStrategyConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStrategyConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateStrategyConfigResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetStrategyStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StrategyId    string                 `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStrategyStateRequest) Reset() {
	*x = GetStrategyStateRequest{}
	mi := &file_strategy_v1_strategy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStrategyStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategyStateRequest) ProtoMessage() {}

func (x *GetStrategyStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_v1_strategy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyStateRequest.ProtoReflect.Descriptor instead.
func (*GetStrategyStateRequest) Descriptor() ([]byte, []int) {
	return file_strategy_v1_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *GetStrategyStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetStrategyStateRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

type GetStrategyStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Status        StrategyStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=api.strategy.v1.StrategyStatus" json:"status,omitempty"`
	CurrentConfig *StrategyConfig        `protobuf:"bytes,3,opt,name=current_config,json=currentConfig,proto3" json:"current_config,omitempty"`
	// Real-time calculated evaluation telemetry
	TotalPnl            float64 `protobuf:"fixed64,4,opt,name=total_pnl,json=totalPnl,proto3" json:"total_pnl,omitempty"` // Current Profit and Loss
	TotalTradesExecuted int64   `protobuf:"varint,5,opt,name=total_trades_executed,json=totalTradesExecuted,proto3" json:"total_trades_executed,omitempty"`
	// Current open exposures managed by this agent (Symbol -> Current Net Quantity)
	ActivePositions map[string]float64     `protobuf:"bytes,6,rep,name=active_positions,json=activePositions,proto3" json:"active_positions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	StatusCheckedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=status_checked_at,json=statusCheckedAt,proto3" json:"status_checked_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStrategyStateResponse) Reset() {
	*x = GetStrategyStateResponse{}
	mi := &file_strategy_v1_strategy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStrategyStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategyStateResponse) ProtoMessage() {}

func (x *GetStrategyStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_v1_strategy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyStateResponse.ProtoReflect.Descriptor instead.
func (*GetStrategyStateResponse) Descriptor() ([]byte, []int) {
	return file_strategy_v1_strategy_proto_rawDescGZIP(), []int{4}
}

func (x *GetStrategyStateResponse) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *GetStrategyStateResponse) GetStatus() StrategyStatus {
	if x != nil {
		return x.Status
	}
	return StrategyStatus_STRATEGY_STATUS_UNSPECIFIED
}

func (x *GetStrategyStateResponse) GetCurrentConfig() *StrategyConfig {
	if x != nil {
		return x.CurrentConfig
	}
	return nil
}

func (x *GetStrategyStateResponse) GetTotalPnl() float64 {
	if x != nil {
		return x.TotalPnl
	}
	return 0
}

func (x *GetStrategyStateResponse) GetTotalTradesExecuted() int64 {
	if x != nil {
		return x.TotalTradesExecuted
	}
	return 0
}

func (x *GetStrategyStateResponse) GetActivePositions() map[string]float64 {
	if x != nil {
		return x.ActivePositions
	}
	return nil
}

func (x *GetStrategyStateResponse) GetStatusCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StatusCheckedAt
	}
	return nil
}

var File_strategy_v1_strategy_proto protoreflect.FileDescriptor

const file_strategy_v1_strategy_proto_rawDesc = "" +
	"\n" +
	"\x1astrategy/v1/strategy.proto\x12\x0fapi.strategy.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x03\n" +
	"\x0eStrategyConfig\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.api.strategy.v1.StrategyTypeR\x04type\x12*\n" +
	"\x11max_position_size\x18\x03 \x01(\x01R\x0fmaxPositionSize\x120\n" +
	"\x14stop_loss_percentage\x18\x04 \x01(\x01R\x12stopLossPercentage\x124\n" +
	"\x16take_profit_percentage\x18\x05 \x01(\x01R\x14takeProfitPercentage\x12O\n" +
	"\n" +
	"parameters\x18\x06 \x03(\v2/.api.strategy.v1.StrategyConfig.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\x1bUpdateStrategyConfigRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12>\n" +
	"\n" +
	"new_config\x18\x02 \x01(\v2\x1f.api.strategy.v1.StrategyConfigR\tnewConfig\"\x8d\x01\n" +
	"\x1cUpdateStrategyConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Y\n" +
	"\x17GetStrategyStateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vstrategy_id\x18\x02 \x01(\tR\n" +
	"strategyId\"\x84\x04\n" +
	"\x18GetStrategyStateResponse\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.api.strategy.v1.StrategyStatusR\x06status\x12F\n" +
	"\x0ecurrent_config\x18\x03 \x01(\v2\x1f.api.strategy.v1.StrategyConfigR\rcurrentConfig\x12\x1b\n" +
	"\ttotal_pnl\x18\x04 \x01(\x01R\btotalPnl\x122\n" +
	"\x15total_trades_executed\x18\x05 \x01(\x03R\x13totalTradesExecuted\x12i\n" +
	"\x10active_positions\x18\x06 \x03(\v2>.api.strategy.v1.GetStrategyStateResponse.ActivePositionsEntryR\x0factivePositions\x12F\n" +
	"\x11status_checked_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0fstatusCheckedAt\x1aB\n" +
	"\x14ActivePositionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01*\x97\x01\n" +
	"\fStrategyType\x12\x1d\n" +
	"\x19STRATEGY_TYPE_UNSPECIFIED\x10\x00\x12*\n" +
	"&STRATEGY_TYPE_MOVING_AVERAGE_CROSSOVER\x10\x01\x12 \n" +
	"\x1cSTRATEGY_TYPE_MEAN_REVERSION\x10\x02\x12\x1a\n" +
	"\x16STRATEGY_TYPE_MOMENTUM\x10\x03*\x9f\x01\n" +
	"\x0eStrategyStatus\x12\x1f\n" +
	"\x1bSTRATEGY_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14STRATEGY_STATUS_IDLE\x10\x01\x12\x1b\n" +
	"\x17STRATEGY_STATUS_RUNNING\x10\x02\x12\x1a\n" +
	"\x16STRATEGY_STATUS_PAUSED\x10\x03\x12\x19\n" +
	"\x15STRATEGY_STATUS_ERROR\x10\x042\xef\x01\n" +
	"\x0fStrategyService\x12s\n" +
	"\x14UpdateStrategyConfig\x12,.api.strategy.v1.UpdateStrategyConfigRequest\x1a-.api.strategy.v1.UpdateStrategyConfigResponse\x12g\n" +
	"\x10GetStrategyState\x12(.api.strategy.v1.GetStrategyStateRequest\x1a).api.strategy.v1.GetStrategyStateResponseB4Z2github.com/opticSquid/ticksim/strategy/v1;strategyb\x06proto3"

var (
	file_strategy_v1_strategy_proto_rawDescOnce sync.Once
	file_strategy_v1_strategy_proto_rawDescData []byte
)

func file_strategy_v1_strategy_proto_rawDescGZIP() []byte {
	file_strategy_v1_strategy_proto_rawDescOnce.Do(func() {
		file_strategy_v1_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_strategy_v1_strategy_proto_rawDesc), len(file_strategy_v1_strategy_proto_rawDesc)))
	})
	return file_strategy_v1_strategy_proto_rawDescData
}

var file_strategy_v1_strategy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_strategy_v1_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_strategy_v1_strategy_proto_goTypes = []any{
	(StrategyType)(0),                    // 0: api.strategy.v1.StrategyType
	(StrategyStatus)(0),                  // 1: api.strategy.v1.StrategyStatus
	(*StrategyConfig)(nil),               // 2: api.strategy.v1.StrategyConfig
	(*UpdateStrategyConfigRequest)(nil),  // 3: api.strategy.v1.UpdateStrategyConfigRequest
	(*UpdateStrategyConfigResponse)(nil), // 4: api.strategy.v1.UpdateStrategyConfigResponse
	(*GetStrategyStateRequest)(nil),      // 5: api.strategy.v1.GetStrategyStateRequest
	(*GetStrategyStateResponse)(nil),     // 6: api.strategy.v1.GetStrategyStateResponse
	nil,                                  // 7: api.strategy.v1.StrategyConfig.ParametersEntry
	nil,                                  // 8: api.strategy.v1.GetStrategyStateResponse.ActivePositionsEntry
	(*timestamppb.Timestamp)(nil),        // 9: google.protobuf.Timestamp
}
var file_strategy_v1_strategy_proto_depIdxs = []int32{
	0,  // 0: api.strategy.v1.StrategyConfig.type:type_name -> api.strategy.v1.StrategyType
	7,  // 1: api.strategy.v1.StrategyConfig.parameters:type_name -> api.strategy.v1.StrategyConfig.ParametersEntry
	2,  // 2: api.strategy.v1.UpdateStrategyConfigRequest.new_config:type_name -> api.strategy.v1.StrategyConfig
	9,  // 3: api.strategy.v1.UpdateStrategyConfigResponse.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: api.strategy.v1.GetStrategyStateResponse.status:type_name -> api.strategy.v1.StrategyStatus
	2,  // 5: api.strategy.v1.GetStrategyStateResponse.current_config:type_name -> api.strategy.v1.StrategyConfig
	8,  // 6: api.strategy.v1.GetStrategyStateResponse.active_positions:type_name -> api.strategy.v1.GetStrategyStateResponse.ActivePositionsEntry
	9,  // 7: api.strategy.v1.GetStrategyStateResponse.status_checked_at:type_name -> google.protobuf.Timestamp
	3,  // 8: api.strategy.v1.StrategyService.UpdateStrategyConfig:input_type -> api.strategy.v1.UpdateStrategyConfigRequest
	5,  // 9: api.strategy.v1.StrategyService.GetStrategyState:input_type -> api.strategy.v1.GetStrategyStateRequest
	4,  // 10: api.strategy.v1.StrategyService.UpdateStrategyConfig:output_type -> api.strategy.v1.UpdateStrategyConfigResponse
	6,  // 11: api.strategy.v1.StrategyService.GetStrategyState:output_type -> api.strategy.v1.GetStrategyStateResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_strategy_v1_strategy_proto_init() }
func file_strategy_v1_strategy_proto_init() {
	if File_strategy_v1_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_strategy_v1_strategy_proto_rawDesc), len(file_strategy_v1_strategy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strategy_v1_strategy_proto_goTypes,
		DependencyIndexes: file_strategy_v1_strategy_proto_depIdxs,
		EnumInfos:         file_strategy_v1_strategy_proto_enumTypes,
		MessageInfos:      file_strategy_v1_strategy_proto_msgTypes,
	}.Build()
	File_strategy_v1_strategy_proto = out.File
	file_strategy_v1_strategy_proto_goTypes = nil
	file_strategy_v1_strategy_proto_depIdxs = nil
}
